import NavBar from "@components/navbar/NavBar";
import Footer from "@components/navbar/Footer";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AppLayout({ children }) {
    return (
        <div className="client-portal">
            {/* Example: client portal sidebar */}
            <aside>Sidebar</aside>
            <main>{children}</main>
        </div>
    )
}
