import React from 'react'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

type AppLayoutProps = {
    children: React.ReactNode
}

const AppLayout: React.FC<AppLayoutProps> = ({ children }) => {
    return (
        <div className="client-portal">
            <main>{children}</main>
        </div>
    )
}
export default AppLayout
