"use client"
import {Providers} from "../../Providers";
import {useState} from "react";
import {Bars3Icon} from "@heroicons/react/24/solid";
import SideBar from "@features/dashboard/SideBar";


// export const metadata = {
//     title: 'Next.js',
//     description: 'Generated by Next.js',
// }

export default function DashboardLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    const [open, setOpen] = useState(false);

    return (
        <html lang="en">
        <body>
        <div className="flex h-screen">
            <SideBar open={open} setOpen={setOpen} />
            {open && (
                <div
                    className="fixed inset-0 bg-black/50 z-30 lg:hidden"
                    onClick={() => setOpen(false)}
                />
            )}
            <main className="flex-1 bg-gray-50 overflow-y-auto">
                <div className="lg:hidden flex items-center justify-between p-4 border-b">
                    <button onClick={() => setOpen(true)} className="text-gray-700">
                        <Bars3Icon className="h-4 w-4" />
                    </button>
                </div>

                <div className="p-4 lg:p-6">
                    <p className="mt-4 text-gray-600">
                        {children}
                    </p>
                </div>
            </main>
        </div>
        </body>
        </html>
    )
}
