'use client'
import { Providers } from '../../Providers'
import { useState } from 'react'
import { Bars3Icon } from '@heroicons/react/24/solid'
import SideBar from '@features/dashboard/SideBar'
import { useAuthGuard } from '@hooks/hooks'

// export const metadata = {
//     title: 'Next.js',
//     description: 'Generated by Next.js',
// }

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
    const [open, setOpen] = useState(false)
    useAuthGuard('ADMIN')

    return (
        <div className="flex h-screen">
            <SideBar open={open} setOpen={setOpen} />
            {open && <div className="fixed inset-0 z-30 bg-black/50 lg:hidden" onClick={() => setOpen(false)} />}
            <main className="flex-1 overflow-y-auto bg-gray-50">
                <div className="flex items-center justify-between border-b p-4 lg:hidden">
                    <button onClick={() => setOpen(true)} className="text-gray-700">
                        <Bars3Icon className="h-4 w-4" />
                    </button>
                </div>

                <div className="p-4 lg:p-6">
                    <div className="mt-4 text-gray-600">{children}</div>
                </div>
            </main>
        </div>
    )
}
