import NavBar from "@components/navbar/NavBar";
import Footer from "@components/navbar/Footer";
import {Providers} from "../Providers";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function SiteLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <NavBar />
      <body>{children}</body>
      <Footer />
    </html>
  )
}
