// "use client";

"use client";

import NavBar from "@components/navbar/NavBar";
import Footer from "@components/navbar/Footer";
import {Providers} from "../Providers";
import {useEffect, useState} from "react";
import Layout from "@components/layout/Layout";
import {useStore} from "react-redux";
import {initAuth} from "@store/init";

// export const metadata = {
//   title: 'Reforme Pilates',
//   description: 'Generated by Next.js',
// }

export default function SiteLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const store = useStore();
  useEffect(() => {
    initAuth(store);
  }, [store]);

  return (
    <html lang="en">

        <body>
          <NavBar />
            <Layout>
                <div className="min-h-[65vh]">{children}</div>
            </Layout>
          <Footer />
        </body>
    </html>
  )
}
