// "use client";

import NavBar from "@components/navbar/NavBar";
import Footer from "@components/navbar/Footer";
import {Providers} from "../Providers";
import { useState } from "react";
import Layout from "@components/layout/Layout";

export const metadata = {
  title: 'Reforme Pilates',
  description: 'Generated by Next.js',
}

export default function SiteLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <NavBar />
        <body>
        <Layout>
            {children}
        </Layout>
        </body>
      <Footer />
    </html>
  )
}
